import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { CartIcon } from "@/components/CartIcon";
import Navbar from "@/components/NavBar";
import { MiniCart } from "@/lib/cart/component/MiniCart";
import { cn } from "@/lib/utils";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal?: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(spaceGrotesk.variable, "font-sans")}>
      <body className="antialiased">
        <Navbar
          miniCart={
            <Suspense fallback={<CartIcon numberOfItems={0} />}>
              <MiniCart />
            </Suspense>
          }
        />
        {children}
        {modal}
      </body>
    </html>
  );
}
